plugins {
    id 'java'
    id 'idea'
    id 'eclipse'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '7.0.17'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

sourceSets {
    client {
        java.srcDir 'src/client/java'
        resources.srcDir 'src/client/resources'
        java.exclude('org/daylight/mixin/**')
        java.exclude('org/daylight/features/**')
        java.exclude('org/daylight/IFeatureManager.java')
        java.exclude('org/daylight/IRenderableFeature.java')
        java.exclude('org/daylight/CustomCatState.java')
        java.exclude('org/daylight/CustomCatTextureHolder.java')
        java.exclude('org/daylight/IShadowHolder.java')
        java.exclude('org/daylight/IElementWVertexConsumerProvider.java')
        java.exclude('org/daylight/IModifiableGuiElement.java')
        java.exclude('org/daylight/util/ModStateUtils.java')
        java.exclude('org/daylight/util/StateStorage.java')
        compileClasspath += sourceSets.main.output + configurations.compileClasspath
        runtimeClasspath += output + compileClasspath + configurations.runtimeClasspath
    }
}

configurations {
    clientImplementation.extendsFrom(implementation)
    clientCompileOnly.extendsFrom(compileOnly)
    clientRuntimeOnly.extendsFrom(runtimeOnly)
    clientAnnotationProcessor.extendsFrom(annotationProcessor)
}

repositories {
    minecraft.mavenizer(it)
    mavenCentral()
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}")
    implementation "net.minecraftforge:eventbus:7.0.1"
    annotationProcessor "org.spongepowered:mixin:0.8.7:processor"
}

minecraft {
    mappings channel: project.mappings_channel, version: project.mappings_version

    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run')
            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
        }

        register('client') {
            jvmArgs '-XstartOnFirstThread'
        }
        register('server') {
            args '--nogui'
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

java {
    withSourcesJar()
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

jar {
    inputs.property "archivesName", project.base.archivesName

    manifest {
        attributes(
                'MixinConfigs': 'catify.mixins.json'
        )
    }

    from(sourceSets.client.output)

    from("LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }
}

tasks.register('printClientClasspath') {
    doLast {
        println("clientCompileClasspath files:")
        configurations.clientCompileClasspath.files.each { f ->
            println(" - " + f.absolutePath)
        }
    }
}